from __future__ import annotations

FIGURE_FILE_PREFIXES = {
    "sample_clustering_dendrogram": "F01_Sample_Clustering_Dendrogram",
    "transcriptome_pca": "F02_Transcriptome_PCA",
    "transcriptome_pca_subgroups": "F03_Transcriptome_PCA_Subgroups",
    "transcriptome_pca_pairs": "F04_Transcriptome_PCA_Pairs",
    "transcriptome_pca_pairs_subgroups": "F05_Transcriptome_PCA_Pairs_Subgroups",
    "metabolome_pca": "F06_Metabolome_PCA",
    "metabolome_pca_subgroups": "F07_Metabolome_PCA_Subgroups",
    "metabolome_pca_pairs": "F08_Metabolome_PCA_Pairs",
    "metabolome_pca_pairs_subgroups": "F09_Metabolome_PCA_Pairs_Subgroups",
    "association_evidence_upset": "F10_Association_Evidence_UpSet",
    "gene_metabolite_correlation_bubble_heatmap": "F11_Gene_Metabolite_Correlation_Bubble_Heatmap",
    "top_gene_metabolite_correlation_heatmaps": "F12_Top_Gene_Metabolite_Correlation_Heatmaps",
    "top_gene_metabolite_pairs": "F13_Top_Gene_Metabolite_Pairs",
    "top_metabolite_group1_violin_box": "F14_Top_Metabolite_Group1_Violin_Box",
    "module_eigengene_heatmap": "F15_Module_Eigengene_Heatmap",
    "module_eigengene_heatmap_group2": "F16_Module_Eigengene_Heatmap_Group2",
    "module_zscore_line_panels": "F17_Module_Zscore_Line_Panels",
    "module_gene_zscore_line_panels": "F18_Module_Gene_Zscore_Line_Panels",
    "module_eigengene_ridge": "F19_Module_Eigengene_Ridge",
    "module_eigengene_ridge_group1": "F20_Module_Eigengene_Ridge_Group1",
    "module_eigengene_group1_violin_box": "F21_Module_Eigengene_Group1_Violin_Box",
    "module_kme_boxplot": "F22_Module_kME_Boxplot",
    "module_metabolite_association_heatmap": "F23_Module_Metabolite_Association_Heatmap",
    "module_metabolite_bubble_plot": "F24_Module_Metabolite_Bubble_Plot",
    "module_top_metabolite_regressions": "F25_Module_Top_Metabolite_Regressions",
    "module_eigengene_metabolite_trend_panels": "F26_Module_Eigengene_Metabolite_Trend_Panels",
    "association_direction_summary": "F27_Association_Direction_Summary",
    "edgeweight_distribution_by_module": "F28_EdgeWeight_Distribution_By_Module",
    "compressed_circos_network": "F29_Compressed_Circos_Network",
    "floating_cnet_circos_network": "F30_Floating_CNet_Circos_Network",
}


TABLE_FILE_PREFIXES = {
    "metabolite_summary": "T01_Metabolite_Association_Summary.csv",
    "high_confidence_network": "T02_High_Confidence_Network.csv",
    "key_gene_summary": "T03_Key_Gene_Summary.csv",
    "gene_module_assignment": "T04_Gene_Module_Assignment.csv",
    "module_metabolite_association": "T05_Module_Metabolite_Association.csv",
    "module_summary": "T06_Module_Summary.csv",
    "gene_scores_audit": "T99_Metabolite_Gene_Scoring_Audit.csv",
}

OBSOLETE_TABLE_FILES = (
    "T01_Metabolite_Gene_Scoring_Table.csv",
    "T01b_Metabolite_Screening_Summary.csv",
    "T02_Total_Association_Network.csv",
    "T03_High_Confidence_Network.csv",
    "T04_Key_Gene_Summary.csv",
    "T05_Metabolite_Association_Summary.csv",
    "T06_Association_Network_Cytoscape.csv",
    "T07_Gene_Module_Assignment.csv",
    "T08_Module_Eigengenes.csv",
    "T09_Module_Metabolite_Association.csv",
    "T10_Module_Summary.csv",
)

OBSOLETE_FIGURE_FILE_PREFIXES = (
    "F02B_Transcriptome_PCA_Subgroups",
    "F02C_Transcriptome_PCA_Pairs",
    "F02D_Transcriptome_PCA_Pairs_Subgroups",
    "F03_Metabolome_PCA",
    "F03B_Metabolome_PCA_Subgroups",
    "F03C_Metabolome_PCA_Pairs",
    "F03D_Metabolome_PCA_Pairs_Subgroups",
    "F04_Top_Gene_Metabolite_Pairs",
    "F04B_Module_Top_Metabolite_Regressions",
    "F04C_Top_Gene_Metabolite_Correlation_Heatmaps",
    "F04D_Top_Metabolite_Group1_Violin_Box",
    "F04E_Gene_Metabolite_Correlation_Bubble_Heatmap",
    "F05_Module_Metabolite_Association_Heatmap",
    "F05A_Module_Eigengene_Heatmap",
    "F05B_Module_Eigengene_Heatmap_Group2",
    "F05C_Module_Zscore_Line_Panels",
    "F05D_Module_Gene_Zscore_Line_Panels",
    "F05E_Module_Eigengene_Ridge",
    "F05F_Module_Eigengene_Ridge_Group1",
    "F05G_Module_Eigengene_Group1_Violin_Box",
    "F05H_Module_kME_Boxplot",
    "F05I_Module_Metabolite_Bubble_Plot",
    "F05J_Association_Direction_Summary",
    "F05K_Module_Eigengene_Metabolite_Trend_Panels",
    "F05L_EdgeWeight_Distribution_By_Module",
    "F06_Compressed_Circos_Network",
    "F07_Floating_CNet_Circos_Network",
    "F08_Association_Evidence_UpSet",
    "F09A_Transcriptome_UMAP_Group1",
    "F09B_Transcriptome_UMAP_Group2",
    "F09C_Metabolome_UMAP_Group1",
    "F09D_Metabolome_UMAP_Group2",
    "F10A_Transcriptome_tSNE_Group1",
    "F10B_Transcriptome_tSNE_Group2",
    "F10C_Metabolome_tSNE_Group1",
    "F10D_Metabolome_tSNE_Group2",
)


__all__ = [
    "FIGURE_FILE_PREFIXES",
    "OBSOLETE_FIGURE_FILE_PREFIXES",
    "OBSOLETE_TABLE_FILES",
    "TABLE_FILE_PREFIXES",
]
